### ISSUE TITLE
Works for the raccoon image, but nothing else

### ISSUE THREAD

**Issue by gituser123456789000** [gpelouze/colormap_to_grayscale#1]
colormap_to_grayscale-master\colormap_to_grayscale-master\colormap_to_grayscale.py:100: RuntimeWarning: invalid value encountered in cast
  image = (image * 255).astype(np.uint8)

**Comment by gpelouze** [comment]
The message that you posted is a warning. Have you checked that it actually fails to save the image? I am still able to run it on other input with the following dependencies:

```
pillow==10.2.0
numpy==1.26.3
scipy==1.12.0
```

However, I would be happy to accept a PR that fixes any issue you encounter.

**Comment by gituser123456789000** [comment]
First, I'm very surprised by your reply, let alone so quickly, since I see this project was posted 5 years ago..

But yes, I checked if it gave a result and it gives a black image..

I converted a copy of the test image to a .jpg a got a complete mess of a result
![input_image](https://github.com/gpelouze/colormap_to_grayscale/assets/156575428/2e52aef5-8a43-4936-8cf0-57e57f0966b0)

**Comment by gituser123456789000** [comment]
As a png, as I said, it give a black image.

As a jpg, it give this as a result
![output](https://github.com/gpelouze/colormap_to_grayscale/assets/156575428/64439e7e-5d30-4bd5-ae63-68e749b0d3ed)

**Comment by gituser123456789000** [comment]
I don't understand how everything works.. I just constantly get stuck and search for answers.. but I know pip list

I see I have the same pillow and scipy versions as you posted, but an older numpy 1.23.1, because I just recently dropped down to python 3.10 to try to run a different program that I didn't have success with

I'll delete python 3.10, so I just have 3.11 and update my numpy if I can figure out how to do that correctly.

Do you get a correct result when trying to convert the image I attached?

**Comment by gpelouze** [comment]
Can you share the color map that you are using as input?

If the image contains colors that are too far from the cmap in the RGB space, they get mapped to transparent pixels in the output PNG. (Read the documentation for the `--max-dist` option.) Therefore you have to pass a color map that corresponds to the one used in the image, otherwise it will not work.

**Comment by gituser123456789000** [comment]
I used the default one that's there already
![input_cmap](https://github.com/gpelouze/colormap_to_grayscale/assets/156575428/9a07b5f8-9d05-404b-94b6-3577693d41d6)

**Comment by gpelouze** [comment]
And this is why it doesn’t work. You have to provide the colormap that is used for your input image.

**Comment by gituser123456789000** [comment]
How would I do that?

The image is from this depth map creation program.
https://github.com/YvanYin/Metric3D
https://huggingface.co/spaces/JUGGHM/Metric3D

But they output the result with this colormap that makes the depth map unusable, instead of in the original grayscale

**Comment by gpelouze** [comment]
Unfortunately is outside of my area of expertise. The goal of `colormap_to_grayscale` is: given a color map and an image rendered with said colormap, infer a grayscale image. Getting the input image *and colormap* is the user's responsibility.

**Comment by gituser123456789000** [comment]
The colormap applied is likely in this code..

https://github.com/YvanYin/Metric3D/blob/main/app.py

I'm not a coder, so I can't exactly decipher it so easily

**Comment by gituser123456789000** [comment]
I see:
gray_to_colormap

 cv_image = np.array(img) 
    img = cv2.cvtColor(cv_image, cv2.COLOR_BGR2RGB)

pred_color = gray_to_colormap(pred_depth)

pred_color_normal = vis_surface_normal(pred_normal)

img = Image.fromarray(pred_color)
    img_normal = Image.fromarray(pred_color_normal)

Any of that tell you what colormap is used?

The color map doesn't seem different from your default.. dark blue to dark red

**Comment by gituser123456789000** [comment]
This Metric3D program is likely the highest quality depth maps available now.

Many people will be wanting to use your program to convert the colored depth map results into the proper grayscale, until those developers set the output to the original grayscale.

But we can't use it if you can't explain how to use it.

How did you make your color map?

**Comment by gituser123456789000** [comment]
![output](https://github.com/gpelouze/colormap_to_grayscale/assets/156575428/03c45b30-41b2-4bfa-a389-7c64b40cd435)

I just added -m 5 to the code to run it and got this, much better result

colormap_to_grayscale.py example/input_cmap.png example/input_image.png -o example/output.png -m 5

You're the coder, the programmer, the inventer, the dev.. you had to have known that. I don't know any coding at all.. too quick to close the issue when it wasn't resolved

**Comment by gpelouze** [comment]
Please read the documentation and make sure that you understand what this options does before using it. What you are doing results in nonsensical output values. It might look like what you wont, but it is not. 

To summarize
- you must provide an image of the color map used by your image as input of `colormap_to_grayscale`
- finding the color map is outside of the scope of this project
- if you use another color map or different values of `-m`, you get crap output

I will now close this issue, because it is drifting very far off topic.
